import React, {useRef, useState} from 'react'

import '../../styles/style.css'
import {ResizablePanes} from 'resizable-panes-react'

import {testResizablePanesId} from './constant'
import {generatePaneModel} from './util'
import {MultiStateButtonGroup} from './multi-state-button-group'
import {addDefaultProps} from '../../utils'
import {noop} from '../../../src/utils/util'

interface IIDMap {
  [id: string]: boolean
}

export const RPTestWrapper = (props: any) => {
  const currentProps = addDefaultProps(props, {
    uniqueId: testResizablePanesId
  })

  const {panesList, initalVisibility, onChangeVisibility = noop} = currentProps

  const [formValues, setFormValues] = useState<any>({
    paneId: '',
    newSize: 0
  })

  const onFormChange = (e: any) => {
    const {name, value} = e.target
    setFormValues({
      ...formValues,
      [name]: value

    })
  }

  const {paneComponentLists, initalVisibility: autoGeneratedInitalVisibility} = generatePaneModel(panesList)
  const initialPaneState = initalVisibility || autoGeneratedInitalVisibility

  const [paneVisibilityState, setPaneVisibilityState] = useState(initialPaneState)

  const [visibilityMap, setVisibilityMap] = useState<IIDMap>(initialPaneState)

  const [resizablePanesVisibility, setResizablePanesVisibility] = useState(true)

  const onRestore = () => {
    setVisibilityMap(initialPaneState)
    apiRef.current.restore()
  }

  const apiRef = useRef <any>({})

  const updateVisibilityMap = (e: any) => {
    const {name, checked} = e
    const newVisibilityMap = {
      ...visibilityMap,
      [name]: checked
    }
    setVisibilityMap(newVisibilityMap)
  }

  return (
    <div className='h-100p w-100p' >

      <div className='d-flex justify-content-center m-10'>
        <button
          data-cy="hide-resizable-panes"
          onClick={() => setResizablePanesVisibility(!resizablePanesVisibility)}
        >
          {resizablePanesVisibility ? 'UnMount' : 'Mount'}
        </button>

        <button
          data-cy="restore-default"
          onClick={onRestore}
        >
          Restore Default
        </button>

        <button
          data-cy="get-map"
          onClick={() => apiRef.current.getState()}
        >
          Get State
        </button>

        <span >
          Pane Id
          <input className='w-56' name='paneId' value={formValues.paneId} onChange={onFormChange} />
        </span>
        <span>
          Size
          <input className='w-56' name='newSize' type='number' value={formValues.newSize} onChange={onFormChange} />
        </span>
        <button
          data-cy="btn-change-size" onClick={() => {
            apiRef.current.setSize(formValues.paneId, Number(formValues.newSize))
          }}
        >Change Size
        </button>

      </div>

      <div className='h-300 w-100p'>
        {
          resizablePanesVisibility &&
          <ResizablePanes
            visibility={visibilityMap}
            onReady={(api) => {
              apiRef.current = api
            }}
            {...currentProps}
            resizerClass='bg-slate-500'
            onChangeVisibility={(...e) => {
              onChangeVisibility(...e)
              setPaneVisibilityState(e[0])
            }}
          >
            {paneComponentLists}
          </ResizablePanes>
        }

      </div>

      <MultiStateButtonGroup stateMap={paneVisibilityState} onClick={updateVisibilityMap} />

    </div>
  )
}
