name: Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
        
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install
    
    - name: Lint/EsLint
      run: |
        npm run lint

    - name: Build
      run: |
        npm run prod

    - name: Component Testing
      run: |
        npm test
        
    - name: Check Coverage
      run: |
        npm run coverage
    
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with: 
        path: cypress/screenshots
        retention-days: 30


    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

