import { IResizableEvent, IJoinClassNameParam, UnitTypes, IBooleanOrUndefined, ISizeStyle } from '../@types';
export declare const toPx: (size: number) => string;
export declare const getSizeKey: (vertical: boolean) => "width" | "height";
export declare const getSizeStyle: (vertical: IBooleanOrUndefined, size: number) => ISizeStyle;
export declare const joinClassName: (param: IJoinClassNameParam, notRequired?: boolean | any) => string;
export declare const getContainerClass: (vertical: boolean, className: string, unit: UnitTypes) => string;
export declare const isTouchEvent: (event: any) => any;
export declare const getResizableEventFromTouch: (e: any, vertical: boolean, previousTouchEvent: any) => IResizableEvent;
export declare const getResizableEventFromMouse: (e: any, vertical: boolean) => IResizableEvent;
export declare const getResizableEvent: (e: any, vertical: boolean, previousTouchEvent: any) => IResizableEvent;
export declare const getDirection: (e: IResizableEvent) => string;
export declare const toArray: (items: any) => any[];
export declare const getSetSize: (node: any, vertical: boolean, addOverFlowLogic?: boolean, addMinSize?: number) => (size: number) => void;
