import { IAnyMap, IPaneModelKey } from '../@types';
import { PaneModel } from '../models/pane-model';
export type INoop = (_: any) => any;
export declare const noop: INoop;
export declare const findById: (list: PaneModel[], _id: string) => PaneModel;
export declare const createMap: (paneList: PaneModel[], ...keys: IPaneModelKey[]) => IAnyMap;
export declare const isUndefinedOrNull: (value: any) => boolean;
export declare const findIndex: (list: any[], value: any, key?: string) => number;
export declare const ratioToNumber: (totalSize: number, maxRatioValue: number, size: number) => number;
export declare const ratioAndRoundOff: (totalSize: number, maxRatioValue: number, size: number) => number;
export declare const addDefaultProps: (props: any, defaultProps: any) => any;
export declare const getObj: <T>(obj: T, ...keys: (keyof T)[]) => any;
