import React, {useRef, useState} from 'react'

import '../../styles/style.css'
import {ResizablePanes} from '../../../src'
import {addDefaultProps} from '../../../src/utils/util'
import {testResizablePanesId} from './constant'
import {generatePaneModel} from './util'
import {MultiStateButtonGroup} from './multi-state-button-group'

interface IIDMap {
  [id: string]: boolean
}

export const RPTestWrapper = (props: any) => {
  const currentProps = addDefaultProps(props, {
    uniqueId: testResizablePanesId
  })

  const {panesList, initalVisibility} = currentProps

  const {paneComponentLists, initalVisibility: autoGeneratedInitalVisibility} = generatePaneModel(panesList)
  const initialPaneState = initalVisibility || autoGeneratedInitalVisibility

  const [paneVisibilityState, setPaneVisibilityState] = useState(initialPaneState)

  const [visibilityMap, setVisibilityMap] = useState<IIDMap>(initialPaneState)

  const [resizablePanesVisibility, setResizablePanesVisibility] = useState(true)

  const onRestore = () => {
    setVisibilityMap(initialPaneState)
    apiRef.current.restoreDefault()
  }

  const apiRef = useRef <any>({})

  const updateVisibilityMap = (e: any) => {
    const {name, checked} = e
    const newVisibilityMap = {
      ...visibilityMap,
      [name]: checked
    }
    setVisibilityMap(newVisibilityMap)
  }

  return (
    <div className='h-100p w-100p' >

      <div className='d-flex justify-content-center m-10'>
        <button
          data-cy="hide-resizable-panes"
          onClick={() => setResizablePanesVisibility(!resizablePanesVisibility)}
        >
          {resizablePanesVisibility ? 'Hide All' : 'Show'}
        </button>

        <button
          data-cy="restore-default"
          onClick={onRestore}
        >
          Restore Default
        </button>

        <button
          data-cy="get-map"
          onClick={() => apiRef.current.getState()}
        >
          Get State
        </button>
      </div>

      <div className='h-300 w-100p'>
        {
          resizablePanesVisibility &&
          <ResizablePanes
            visibility={visibilityMap}
            onReady={(api) => {
              apiRef.current = api
            }}
            {...currentProps}
            onChangeVisibility={setPaneVisibilityState}
          >
            {paneComponentLists}
          </ResizablePanes>
        }

      </div>

      <MultiStateButtonGroup stateMap={paneVisibilityState} onClick={updateVisibilityMap} />

    </div>
  )
}
