name: Build

on:
  schedule:
  - cron: "*/5 * * * *"
  - branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install
    
    - name: Lint/EsLint
      run: |
        npm run lint

    - name: Build
      run: |
        npm run build-prod

    - name: Component Testing
      run: |
        npm run test:cloud
        
    - name: Check Coverage
      run: |
        npm run coverage

